// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Order_Function.Data;

#nullable disable

namespace Order_Function.Migrations
{
    [DbContext(typeof(OrderContext))]
    partial class OrderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Orders.Models.Order", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("cost")
                        .HasColumnType("numeric");

                    b.Property<Guid>("itemId")
                        .HasColumnType("uuid")
                        .HasColumnName("itemId");

                    b.Property<Guid>("merchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchantId");

                    b.Property<string>("notes")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("notes");

                    b.Property<string>("orderStatus")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("orderStatus");

                    b.Property<string>("orderStatusReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("orderTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("qty")
                        .HasColumnType("decimal")
                        .HasColumnName("qty");

                    b.HasKey("id");

                    b.ToTable("ORDERS", "orders");
                });
#pragma warning restore 612, 618
        }
    }
}
